# Dependabot configuration for automated dependency updates
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rishirandhawa"
    assignees:
      - "rishirandhawa"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 2
    reviewers:
      - "rishirandhawa"
    assignees:
      - "rishirandhawa"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "automated"
