blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-username/mcp-protocol-sdk/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/your-username/mcp-protocol-sdk/tree/main/docs
    about: Read the comprehensive documentation and guides
  - name: 🎯 Examples
    url: https://github.com/your-username/mcp-protocol-sdk/tree/main/examples
    about: Check out working examples for common use cases
  - name: 🔧 API Reference
    url: https://docs.rs/mcp-protocol-sdk
    about: Browse the complete API documentation
