name: Benchmarks

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'benches/**'
      - 'Cargo.toml'
  pull_request:
    paths:
      - 'src/**'
      - 'benches/**'
      - 'Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-bench-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-criterion
        run: cargo install cargo-criterion

      - name: Run benchmarks
        run: cargo criterion --all-features

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: target/criterion/reports/index.html
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          comment-on-alert: true
          alert-threshold: '200%'
          fail-on-alert: false

  performance_comparison:
    name: Performance Comparison
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-bench-pr-${{ hashFiles('**/Cargo.lock') }}

      - name: Run PR benchmarks
        run: cargo bench --all-features -- --output-format json | tee pr_benchmark.json

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Run main benchmarks
        run: cargo bench --all-features -- --output-format json | tee main_benchmark.json

      - name: Compare benchmarks
        run: |
          echo "## Benchmark Comparison" >> comparison.md
          echo "Performance comparison between main and this PR:" >> comparison.md
          echo "" >> comparison.md
          
          # This is a simplified comparison - in practice, you'd want to use
          # a more sophisticated tool like criterion-compare
          echo "Benchmark results available in artifacts." >> comparison.md

      - name: Upload comparison
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-comparison
          path: |
            comparison.md
            pr_benchmark.json
            main_benchmark.json
