name: Dependencies

on:
  schedule:
    - cron: '0 2 * * 1' # Monday at 2 AM UTC
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "deps"
          cache-on-failure: true

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Update dependencies
        run: |
          echo "## Dependency Updates" > update_summary.md
          echo "" >> update_summary.md
          
          # Get current versions
          cargo tree --depth 1 --format "{p}" > before.txt
          
          # Update dependencies
          cargo update
          
          # Get new versions
          cargo tree --depth 1 --format "{p}" > after.txt
          
          # Show differences
          echo "### Updated packages:" >> update_summary.md
          echo '```' >> update_summary.md
          comm -13 <(sort before.txt) <(sort after.txt) >> update_summary.md || echo "No changes detected" >> update_summary.md
          echo '```' >> update_summary.md

      - name: Run tests
        run: cargo test --all-features

      - name: Run security audit
        run: |
          cargo install cargo-audit
          cargo audit

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'deps: update dependencies'
          title: 'deps: update dependencies'
          body-path: update_summary.md
          branch: update-dependencies
          delete-branch: true
          labels: |
            dependencies
            automated
