name: Dependencies

# Automated dependency updates with pull request creation
# Requires GH_TOKEN secret with 'repo' and 'pull_request' scopes for PR creation
# Repository Settings → Secrets and variables → Actions → New repository secret:
# Name: GH_TOKEN, Value: <your-personal-access-token>

on:
  schedule:
    - cron: '0 2 * * 1' # Monday at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          # Use PAT for checkout to enable PR creation
          token: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "deps"
          cache-on-failure: true

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Update dependencies
        run: |
          echo "## Dependency Updates" > update_summary.md
          echo "" >> update_summary.md
          
          # Get current versions
          cargo tree --depth 1 --format "{p}" > before.txt
          
          # Update dependencies
          cargo update
          
          # Get new versions
          cargo tree --depth 1 --format "{p}" > after.txt
          
          # Show differences
          echo "### Updated packages:" >> update_summary.md
          echo '```' >> update_summary.md
          comm -13 <(sort before.txt) <(sort after.txt) >> update_summary.md || echo "No changes detected" >> update_summary.md
          echo '```' >> update_summary.md

      - name: Run tests
        run: cargo test --all-features

      - name: Run security audit
        run: |
          cargo install cargo-audit
          cargo audit

      - name: Check PAT availability
        id: check-token
        run: |
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "pat_available=false" >> $GITHUB_OUTPUT
            echo "::warning::GH_TOKEN secret not configured. See .github/SETUP_PAT.md for setup instructions."
          else
            echo "pat_available=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check-token.outputs.pat_available == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          # Use PAT for pull request creation (required for automated PRs)
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'deps: update dependencies'
          title: 'deps: update dependencies'
          body-path: update_summary.md
          branch: update-dependencies
          delete-branch: true
          labels: |
            dependencies
            automated
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: PAT Setup Required
        if: steps.check-token.outputs.pat_available == 'false'
        run: |
          echo "::error::Cannot create pull request - GH_TOKEN secret not configured"
          echo "::error::Repository admin needs to set up Personal Access Token"
          echo "::error::See .github/SETUP_PAT.md for detailed setup instructions"
          echo "::error::Workflow completed successfully but pull request creation was skipped"
          echo ""
          echo "Summary of completed steps:"
          echo "✅ Dependencies updated successfully"
          echo "✅ Tests passed with all features"
          echo "✅ Security audit completed"
          echo "❌ Pull request creation skipped (PAT required)"
          echo ""
          echo "To enable automated pull requests:"
          echo "1. Repository admin generates PAT with 'repo' scope"
          echo "2. Add PAT as repository secret named 'GH_TOKEN'"
          echo "3. See .github/SETUP_PAT.md for step-by-step instructions"
