name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "docs"
          cache-on-failure: true
        
      - name: Generate documentation
        run: |
          cargo doc --all-features --no-deps --document-private-items
          echo '<meta http-equiv="refresh" content="0; url=mcp_protocol_sdk">' > target/doc/index.html
        env:
          RUSTDOCFLAGS: "--cfg docsrs"
        
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/doc
          
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
